# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run ty check src tests
        types: [ python ]
        language: system
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        types: [ python ]
        language: system
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        types: [ python ]
        language: system
