name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.12', '3.13', '3.14' ]

    env:
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: uv sync --locked --all-extras --dev
      - run: docker compose -f docker-compose.testing.yml down -v --remove-orphans
      - run: docker compose -f docker-compose.testing.yml up -d db
      - name: Run tests
        run: |
          uv run --frozen -- coverage run --source=src -m pytest tests
          uv run --frozen -- coverage report --show-missing
          uv run --frozen -- coverage html --title "Coverage for ${{ github.sha}}"
      - run: docker compose -f docker-compose.testing.yml down -v --remove-orphans
      - name: Store coverage files
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true
